version: 0.2
phases:
  install:
    commands:
      - npm install
  build:
    commands:
      - cp src/constants.prod.json src/constants.json
      - npm run build
  post_build:
    commands:
      - rsync -rv dist/ $TARGET_PATH/
